import turtle

def wish_machan():
    window = turtle.Screen()
    window.bgcolor("blue")
    window.title("You're Old..er!")

    vw = turtle.Turtle()
    vw.shape("turtle")
    vw.color("yellow")
    vw.pensize(width=5)
    vw.penup()
    vw.back(200)
    vw.left(90)
    vw.forward(100)
    vw.right(90)
    vw.pendown()
    vw.right(90)
    vw.forward(200)
    vw.back(100)
    vw.left(90)
    vw.forward(100)
    vw.left(90)
    vw.forward(100)
    vw.back(200)
    vw.penup()
    vw.right(90)
    vw.forward(50)
    vw.pendown()
    vw.forward(50)
    vw.circle(50, extent=180)
    vw.forward(50)
    vw.right(180)
    vw.forward(50)
    vw.circle(50, extent=180)
    vw.forward(50)
    vw.left(90)
    vw.forward(200)
    vw.penup()
    vw.left(90)
    vw.forward(150)
    vw.pendown()
    vw.left(90)
    vw.forward(200)
    vw.right(90)
    vw.circle(-100, extent=180)

    window.exitonclick()

wish_machan()